# General settings
seed: 17
is_training: 1
task_name: "default"
des: "test"
comment: "grid search"

# Paths
# tb_log_dir: "/data3/lsf/Pein/Power-Prediction/output/tb_log"
# checkpoint_dir: "/data3/lsf/Pein/Power-Prediction/output/checkpoint"
# best_metrics_dir: "/data3/lsf/Pein/Power-Prediction/output/best_metrics"
log_output_dir: "/data3/lsf/Pein/Power-Prediction/log_output/24-07-16"
output_dir: "/data3/lsf/Pein/Power-Prediction/output/24-07-16"
final_best_metrics_log_path: "/data3/lsf/Pein/Power-Prediction/final_best_metrics.log"
# result_dir: "/data3/lsf/Pein/Power-Prediction/output/result"
data_root_dir: "/data3/lsf/Pein/Power-Prediction/data"
train_path: "train_data_89_withTime.csv"
test_path: "train_data_89_withTime.csv"
# checkpoints: "/data3/lsf/Pein/Power-Prediction/output/checkpoint"

# Data settings
train_val_split: 0.2
target: "power"
inverse: true
num_workers: 8
data: "WindPower"

# Model settings
model: "SimpleMLP"
input_dim: 75
dec_in: 75
output_dim: 1
d_model: 16
n_heads: 4
e_layers: 2
d_layers: 1
hidden_dim: 32
last_hidden_dim: 16
top_k: 5
num_kernels: 6
activation: "gelu"
time_d_model: 128
combine_type: "add"
seq_len: 8
pred_len: 1

# Training settings
exp_settings: null
gradient_clip_val: 2
train_epochs: 5
batch_size: 1100
early_stop_patience: 6
learning_rate: 0.01
loss: "MSE"
lradj: "TST"
pct_start: 0.2
use_amp: false
moving_avg: 25
dropout: 0.1
decomp_method: "moving_avg"
use_norm: 1
down_sampling_layers: 2
down_sampling_window: 2
down_sampling_method: "avg"


# Scheduler settings
scheduler_type: "OneCycleLR"
T_max: 20
weight_decay: 0.0001
patience: 5
Reduce_factor: 0.2

# GPU settings
use_gpu: True
gpu: 0
use_multi_gpu: False
use_all_gpus_for_search: True

# Additional settings
min_y_value: 0.0
