# General settings
general_settings:
  seed: 17
  is_training: 1
  task_name: "default"
  description: "train"
  comment: "optuna search"

# exp_time_str: 'exp_time_str'

# Output Paths
output_paths:
  train_log_dir: "/data3/lsf/Pein/Power-Prediction/train_log/exp_time_str"
  res_output_dir: "/data3/lsf/Pein/Power-Prediction/res_output/exp_time_str"
  final_best_metrics_log_path: "/data3/lsf/Pein/Power-Prediction/final_best_metric/exp_time_str.log"
  optuna_study_dir: "/data3/lsf/Pein/Power-Prediction/optuna_study/exp_time_str"
  wandb_output_dir: "/data3/lsf/Pein/Power-Prediction/wandb_output/optuna/exp_time_str"

# Data paths
data_paths:
  data_root_dir: "/data3/lsf/Pein/Power-Prediction/data"
  train_path: "train_farm_65_withTime.csv"
  test_path: "test_farm_65_withTime.csv"

# Data settings
data_settings:
  train_val_split: 0.2
  target: "power"
  inverse: true
  num_workers: 8
  data: "WindPower"
  scale_x_type: "standard"
  scale_y_type: "standard"

# Model settings
model_settings:
  name: "SimpleMLP"
  token_emb_kernel_size: 3
  input_dim: 51
  dec_in: 51
  output_dim: 1
  d_model: 16
  n_heads: 4
  e_layers: 2
  d_layers: 1
  hidden_dim: 32
  last_hidden_dim: 16
  top_k: 5
  num_kernels: 6
  activation: "gelu"
  time_d_model: 128
  combine_type: "add"
  seq_len: 8
  pred_len: 1
  min_y_value: 0.0
  dropout: 0.1

# Global Settings
exp_settings: null

# Training settings
training_settings:
  gradient_clip_val: 1
  train_epochs: 120
  batch_size: 1100
  early_stop_patience: 15
  learning_rate: 0.01
  loss: "MSE"
  lradj: "TST"
  pct_start: 0.3
  use_amp: false
  moving_avg: 51
  decomp_method: "moving_avg"
  use_norm: 1
  down_sampling_layers: 2
  down_sampling_window: 2
  down_sampling_method: "avg"

# Scheduler settings
scheduler_settings:
  type: "OneCycleLR"
  T_max: 20
  weight_decay: 0.0001
  patience: 5
  reduce_factor: 0.2
  pct_start: 0.3
  eta_min: 1e-6
  warmup_steps: 0

# GPU settings
gpu_settings:
  use_gpu: True
  gpu_id: 0
  use_multi_gpu: False
  use_all_gpus_for_search: False

# Additional settings
additional_settings:

# Logging settings
logging_settings:
  use_wandb: False
